#!/usr/bin/env python3
"""Generate additional seed deck items to reach 40+ (run once, output JSON fragment)."""
from __future__ import annotations

import json
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
SEED = REPO_ROOT / "speedrun" / "data" / "seed_deck.json"

# Template items covering untested flaw/qt/rc schemas
NEW_ITEMS = [
    {
        "id": "lr-0009",
        "section": "LR",
        "stem_type": "qt.flaw",
        "schemas": ["flaw.causal.reversed", "qt.flaw"],
        "difficulty": 3,
        "source": "original",
        "stimulus": "People who sleep less watch more late-night TV. Therefore, watching late-night TV causes insomnia.",
        "question": "The reasoning is most vulnerable to criticism on the grounds that it",
        "choices": [
            {"id": "A", "text": "treats a possible effect as a cause.", "trap": None, "correct": True},
            {"id": "B", "text": "relies on a small sample.", "trap": "trap.out_of_scope", "correct": False},
            {"id": "C", "text": "defines insomnia too narrowly.", "trap": "trap.out_of_scope", "correct": False},
            {"id": "D", "text": "assumes all viewers stay up late.", "trap": "trap.too_strong_extreme", "correct": False},
            {"id": "E", "text": "ignores people who sleep well.", "trap": "trap.too_weak", "correct": False},
        ],
        "two_answer_fork": {"runner_up": "E", "why_runner_up_wrong": "E is too weak; A names reversed causation."},
        "paraphrases": [{"stimulus": "Those who exercise less consume more sugary snacks, so sugary snacks cause laziness.", "question": "The argument is flawed because it"}],
    },
    {
        "id": "lr-0010",
        "section": "LR",
        "stem_type": "qt.weaken",
        "schemas": ["flaw.causal.post_hoc", "qt.weaken"],
        "difficulty": 2,
        "source": "original",
        "stimulus": "After the town installed speed cameras, accidents fell. The cameras clearly prevent accidents.",
        "question": "Which one of the following, if true, most weakens the argument?",
        "choices": [
            {"id": "A", "text": "Accidents also fell in neighboring towns that did not install cameras.", "trap": None, "correct": True},
            {"id": "B", "text": "Drivers dislike being photographed.", "trap": "trap.out_of_scope", "correct": False},
            {"id": "C", "text": "The cameras are expensive.", "trap": "trap.out_of_scope", "correct": False},
            {"id": "D", "text": "Some accidents still occur.", "trap": "trap.too_weak", "correct": False},
            {"id": "E", "text": "Speed limits were lowered the same month.", "trap": "trap.half_right", "correct": False},
        ],
        "two_answer_fork": {"runner_up": "E", "why_runner_up_wrong": "E is an alternative cause but A shows the drop without cameras — stronger weaken of the causal claim."},
        "paraphrases": [{"stimulus": "After the library extended hours, attendance rose, proving longer hours cause more reading.", "question": "Which weakens the argument?"}],
    },
    {
        "id": "lr-0011",
        "section": "LR",
        "stem_type": "qt.flaw",
        "schemas": ["flaw.conditional.nec_suff_confusion", "qt.flaw"],
        "difficulty": 3,
        "source": "original",
        "stimulus": "Only members may vote. Sam voted, so Sam must be a member.",
        "question": "The reasoning is flawed because it",
        "choices": [
            {"id": "A", "text": "confuses a necessary condition for membership with a sufficient one.", "trap": None, "correct": True},
            {"id": "B", "text": "assumes all members vote.", "trap": "trap.reversed_relationship", "correct": False},
            {"id": "C", "text": "fails to define membership.", "trap": "trap.out_of_scope", "correct": False},
            {"id": "D", "text": "relies on Sam's testimony.", "trap": "trap.out_of_scope", "correct": False},
            {"id": "E", "text": "ignores non-members who want to vote.", "trap": "trap.out_of_scope", "correct": False},
        ],
        "two_answer_fork": {"runner_up": "B", "why_runner_up_wrong": "B reverses the relationship; the error is treating voting as sufficient for membership when it is only necessary."},
    },
    {
        "id": "lr-0012",
        "section": "LR",
        "stem_type": "qt.flaw",
        "schemas": ["flaw.conditional.mistaken_negation", "qt.flaw"],
        "difficulty": 3,
        "source": "original",
        "stimulus": "If the lab is safe, then technicians wear goggles. Technicians are not wearing goggles, so the lab is not safe.",
        "question": "The argument's reasoning is questionable because it",
        "choices": [
            {"id": "A", "text": "treats the absence of one safety measure as proof the lab is unsafe.", "trap": None, "correct": True},
            {"id": "B", "text": "assumes goggles are uncomfortable.", "trap": "trap.out_of_scope", "correct": False},
            {"id": "C", "text": "confuses necessary and sufficient conditions.", "trap": "trap.reversed_relationship", "correct": False},
            {"id": "D", "text": "overlooks that some labs are safe without goggles.", "trap": "trap.half_right", "correct": False},
            {"id": "E", "text": "fails to count the technicians.", "trap": "trap.out_of_scope", "correct": False},
        ],
        "two_answer_fork": {"runner_up": "C", "why_runner_up_wrong": "C describes a different error; A matches denying the consequent from a conditional that may not be biconditional."},
    },
    {
        "id": "lr-0013",
        "section": "LR",
        "stem_type": "qt.flaw",
        "schemas": ["flaw.sampling.appeal_to_ignorance", "qt.flaw"],
        "difficulty": 2,
        "source": "original",
        "stimulus": "No one has proved the new pesticide is harmful, so it must be safe.",
        "question": "The reasoning is most vulnerable because it",
        "choices": [
            {"id": "A", "text": "treats a lack of evidence as evidence of absence.", "trap": None, "correct": True},
            {"id": "B", "text": "assumes pesticides are always harmful.", "trap": "trap.opposite", "correct": False},
            {"id": "C", "text": "relies on expert testimony.", "trap": "trap.out_of_scope", "correct": False},
            {"id": "D", "text": "fails to define harmful.", "trap": "trap.out_of_scope", "correct": False},
            {"id": "E", "text": "ignores farmers' opinions.", "trap": "trap.out_of_scope", "correct": False},
        ],
        "two_answer_fork": {"runner_up": "D", "why_runner_up_wrong": "D is out of scope; A is the appeal-to-ignorance flaw."},
    },
    {
        "id": "lr-0014",
        "section": "LR",
        "stem_type": "qt.flaw",
        "schemas": ["flaw.scope.equivocation", "qt.flaw"],
        "difficulty": 4,
        "source": "original",
        "stimulus": "Banks are beside rivers. Financial institutions are important. So financial institutions are beside rivers.",
        "question": "The argument is flawed because it",
        "choices": [
            {"id": "A", "text": "uses the word 'bank' in two different senses.", "trap": None, "correct": True},
            {"id": "B", "text": "assumes all rivers have banks.", "trap": "trap.half_right", "correct": False},
            {"id": "C", "text": "overlooks small financial institutions.", "trap": "trap.out_of_scope", "correct": False},
            {"id": "D", "text": "fails to mention loans.", "trap": "trap.out_of_scope", "correct": False},
            {"id": "E", "text": "relies on geography.", "trap": "trap.out_of_scope", "correct": False},
        ],
        "two_answer_fork": {"runner_up": "B", "why_runner_up_wrong": "B misses the pun; A identifies equivocation."},
    },
    {
        "id": "lr-0015",
        "section": "LR",
        "stem_type": "qt.flaw",
        "schemas": ["flaw.structure.circular", "qt.flaw"],
        "difficulty": 3,
        "source": "original",
        "stimulus": "This book is trustworthy because the author says so, and the author is trustworthy because the book says so.",
        "question": "The reasoning is flawed because it",
        "choices": [
            {"id": "A", "text": "rests on mutually reinforcing claims without independent support.", "trap": None, "correct": True},
            {"id": "B", "text": "assumes all books are trustworthy.", "trap": "trap.too_strong_extreme", "correct": False},
            {"id": "C", "text": "fails to quote the book.", "trap": "trap.out_of_scope", "correct": False},
            {"id": "D", "text": "ignores critics.", "trap": "trap.out_of_scope", "correct": False},
            {"id": "E", "text": "relies on a single author.", "trap": "trap.out_of_scope", "correct": False},
        ],
        "two_answer_fork": {"runner_up": "E", "why_runner_up_wrong": "E is irrelevant; A describes circular reasoning."},
    },
    {
        "id": "lr-0016",
        "section": "LR",
        "stem_type": "qt.flaw",
        "schemas": ["flaw.structure.ad_hominem", "qt.flaw"],
        "difficulty": 2,
        "source": "original",
        "stimulus": "You shouldn't trust Dr. Lee's diet advice; she eats dessert every night.",
        "question": "The argument is most vulnerable because it",
        "choices": [
            {"id": "A", "text": "attacks the person rather than the claim.", "trap": None, "correct": True},
            {"id": "B", "text": "assumes dessert is unhealthy.", "trap": "trap.out_of_scope", "correct": False},
            {"id": "C", "text": "fails to define diet.", "trap": "trap.out_of_scope", "correct": False},
            {"id": "D", "text": "overlooks other doctors.", "trap": "trap.out_of_scope", "correct": False},
            {"id": "E", "text": "relies on anecdotal evidence about nutrition.", "trap": "trap.half_right", "correct": False},
        ],
        "two_answer_fork": {"runner_up": "E", "why_runner_up_wrong": "E mischaracterizes the flaw; A is ad hominem."},
    },
    {
        "id": "lr-0017",
        "section": "LR",
        "stem_type": "qt.flaw",
        "schemas": ["flaw.structure.straw_man", "qt.flaw"],
        "difficulty": 3,
        "source": "original",
        "stimulus": "Senator Park wants to cut all funding for parks. Clearly she hates nature.",
        "question": "The reasoning is flawed because it",
        "choices": [
            {"id": "A", "text": "misrepresents the senator's position to make it easier to attack.", "trap": None, "correct": True},
            {"id": "B", "text": "assumes all senators dislike nature.", "trap": "trap.too_strong_extreme", "correct": False},
            {"id": "C", "text": "fails to define funding.", "trap": "trap.out_of_scope", "correct": False},
            {"id": "D", "text": "ignores urban parks.", "trap": "trap.out_of_scope", "correct": False},
            {"id": "E", "text": "relies on public opinion polls.", "trap": "trap.out_of_scope", "correct": False},
        ],
        "two_answer_fork": {"runner_up": "B", "why_runner_up_wrong": "B overgeneralizes; A is straw man."},
    },
    {
        "id": "lr-0018",
        "section": "LR",
        "stem_type": "qt.flaw",
        "schemas": ["flaw.structure.false_dilemma", "qt.flaw"],
        "difficulty": 2,
        "source": "original",
        "stimulus": "Either we ban all cars or accept permanent gridlock. We cannot ban all cars, so we must accept gridlock.",
        "question": "The argument is vulnerable because it",
        "choices": [
            {"id": "A", "text": "presumes only two options when others may exist.", "trap": None, "correct": True},
            {"id": "B", "text": "assumes gridlock is permanent.", "trap": "trap.half_right", "correct": False},
            {"id": "C", "text": "fails to define cars.", "trap": "trap.out_of_scope", "correct": False},
            {"id": "D", "text": "ignores public transit entirely.", "trap": "trap.half_right", "correct": False},
            {"id": "E", "text": "relies on emotional language.", "trap": "trap.out_of_scope", "correct": False},
        ],
        "two_answer_fork": {"runner_up": "D", "why_runner_up_wrong": "D hints at alternatives but A states the false dilemma directly."},
    },
    {
        "id": "lr-0019",
        "section": "LR",
        "stem_type": "qt.flaw",
        "schemas": ["flaw.structure.appeal_authority_emotion", "qt.flaw"],
        "difficulty": 2,
        "source": "original",
        "stimulus": "This medicine must work; a famous actor says it changed his life and the commercial made me cry.",
        "question": "The reasoning is most vulnerable because it",
        "choices": [
            {"id": "A", "text": "relies on celebrity and emotion instead of evidence.", "trap": None, "correct": True},
            {"id": "B", "text": "assumes all medicines work.", "trap": "trap.too_strong_extreme", "correct": False},
            {"id": "C", "text": "fails to mention side effects.", "trap": "trap.out_of_scope", "correct": False},
            {"id": "D", "text": "ignores cost.", "trap": "trap.out_of_scope", "correct": False},
            {"id": "E", "text": "relies on a single actor.", "trap": "trap.half_right", "correct": False},
        ],
        "two_answer_fork": {"runner_up": "E", "why_runner_up_wrong": "E is incomplete; A captures both authority and emotion appeals."},
    },
    {
        "id": "lr-0020",
        "section": "LR",
        "stem_type": "qt.flaw",
        "schemas": ["flaw.structure.comparison", "qt.flaw"],
        "difficulty": 3,
        "source": "original",
        "stimulus": "Our software costs less than theirs, so it must be the better product.",
        "question": "The argument is flawed because it",
        "choices": [
            {"id": "A", "text": "treats lower price as proof of superior quality.", "trap": None, "correct": True},
            {"id": "B", "text": "assumes both products are identical.", "trap": "trap.half_right", "correct": False},
            {"id": "C", "text": "fails to mention features.", "trap": "trap.out_of_scope", "correct": False},
            {"id": "D", "text": "ignores customer service.", "trap": "trap.out_of_scope", "correct": False},
            {"id": "E", "text": "relies on a single competitor.", "trap": "trap.out_of_scope", "correct": False},
        ],
        "two_answer_fork": {"runner_up": "B", "why_runner_up_wrong": "B is not the stated error; A is the flawed price-quality comparison."},
    },
    {
        "id": "lr-0021",
        "section": "LR",
        "stem_type": "qt.flaw",
        "schemas": ["flaw.structure.self_contradiction", "qt.flaw"],
        "difficulty": 3,
        "source": "original",
        "stimulus": "No generalizations are reliable, and that is always true.",
        "question": "The statement is most vulnerable because it",
        "choices": [
            {"id": "A", "text": "asserts a general rule that contradicts itself.", "trap": None, "correct": True},
            {"id": "B", "text": "assumes all generalizations are false.", "trap": "trap.half_right", "correct": False},
            {"id": "C", "text": "fails to define reliability.", "trap": "trap.out_of_scope", "correct": False},
            {"id": "D", "text": "ignores statistical methods.", "trap": "trap.out_of_scope", "correct": False},
            {"id": "E", "text": "relies on a single example.", "trap": "trap.out_of_scope", "correct": False},
        ],
        "two_answer_fork": {"runner_up": "B", "why_runner_up_wrong": "B misreads the claim; A is self-contradiction."},
    },
    {
        "id": "lr-0022",
        "section": "LR",
        "stem_type": "qt.sufficient_assumption",
        "schemas": ["qt.sufficient_assumption"],
        "difficulty": 3,
        "source": "original",
        "stimulus": "The exhibit will be popular only if it includes interactive displays. It will include interactive displays.",
        "question": "Which assumption, if added, allows the conclusion that the exhibit will be popular?",
        "choices": [
            {"id": "A", "text": "Interactive displays are sufficient to guarantee popularity.", "trap": None, "correct": True},
            {"id": "B", "text": "All popular exhibits are expensive.", "trap": "trap.out_of_scope", "correct": False},
            {"id": "C", "text": "The exhibit will be free.", "trap": "trap.out_of_scope", "correct": False},
            {"id": "D", "text": "Some exhibits lack interactive displays.", "trap": "trap.too_weak", "correct": False},
            {"id": "E", "text": "Popularity requires advertising.", "trap": "trap.out_of_scope", "correct": False},
        ],
        "two_answer_fork": {"runner_up": "D", "why_runner_up_wrong": "D is too weak; A bridges only-if to therefore with a sufficient condition."},
    },
    {
        "id": "lr-0023",
        "section": "LR",
        "stem_type": "qt.inference_must_be_true",
        "schemas": ["qt.inference_must_be_true"],
        "difficulty": 3,
        "source": "original",
        "stimulus": "Every delegate speaks either French or Spanish. No delegate who speaks French attends the evening session.",
        "question": "If Juan is a delegate who attends the evening session, which must be true?",
        "choices": [
            {"id": "A", "text": "Juan speaks Spanish.", "trap": None, "correct": True},
            {"id": "B", "text": "Juan speaks both French and Spanish.", "trap": "trap.could_be_true", "correct": False},
            {"id": "C", "text": "Juan does not speak Spanish.", "trap": "trap.opposite", "correct": False},
            {"id": "D", "text": "Juan is not a delegate.", "trap": "trap.opposite", "correct": False},
            {"id": "E", "text": "Some delegates speak neither language.", "trap": "trap.out_of_scope", "correct": False},
        ],
        "two_answer_fork": {"runner_up": "B", "why_runner_up_wrong": "B could be true but is not forced; evening attendance rules out French, leaving Spanish."},
    },
    {
        "id": "lr-0024",
        "section": "LR",
        "stem_type": "qt.most_strongly_supported",
        "schemas": ["qt.most_strongly_supported"],
        "difficulty": 2,
        "source": "original",
        "stimulus": "After the fee was removed, museum visits rose sharply among students but changed little among retirees.",
        "question": "Which is most strongly supported?",
        "choices": [
            {"id": "A", "text": "Removing the fee likely increased student visits more than retiree visits.", "trap": None, "correct": True},
            {"id": "B", "text": "Retirees dislike museums.", "trap": "trap.too_strong_extreme", "correct": False},
            {"id": "C", "text": "The fee was the only barrier for students.", "trap": "trap.too_strong_extreme", "correct": False},
            {"id": "D", "text": "Student visits will keep rising forever.", "trap": "trap.too_strong_extreme", "correct": False},
            {"id": "E", "text": "Retirees stopped visiting.", "trap": "trap.opposite", "correct": False},
        ],
        "two_answer_fork": {"runner_up": "C", "why_runner_up_wrong": "C is too strong; A is the modest comparative supported by the evidence."},
    },
    {
        "id": "lr-0025",
        "section": "LR",
        "stem_type": "qt.principle_identify",
        "schemas": ["qt.principle_identify"],
        "difficulty": 3,
        "source": "original",
        "stimulus": "Because the witness had no motive to lie and her account matched physical evidence, the jury believed her.",
        "question": "Which principle best underlies the reasoning?",
        "choices": [
            {"id": "A", "text": "Testimony should be credited when consistent with evidence and lacking motive to deceive.", "trap": None, "correct": True},
            {"id": "B", "text": "All witnesses with motives lie.", "trap": "trap.too_strong_extreme", "correct": False},
            {"id": "C", "text": "Physical evidence is never wrong.", "trap": "trap.too_strong_extreme", "correct": False},
            {"id": "D", "text": "Juries always believe witnesses.", "trap": "trap.too_strong_extreme", "correct": False},
            {"id": "E", "text": "Motive is irrelevant to credibility.", "trap": "trap.opposite", "correct": False},
        ],
        "two_answer_fork": {"runner_up": "B", "why_runner_up_wrong": "B overstates; A captures the balanced principle used."},
    },
    {
        "id": "lr-0026",
        "section": "LR",
        "stem_type": "qt.principle_apply",
        "schemas": ["qt.principle_apply"],
        "difficulty": 3,
        "source": "original",
        "stimulus": "Principle: A policy should not burden a group unless it produces a compensating benefit to society.",
        "question": "Which situation most clearly violates the principle?",
        "choices": [
            {"id": "A", "text": "A tax on textbooks funds schools but raises costs for low-income students without improving outcomes.", "trap": None, "correct": True},
            {"id": "B", "text": "A toll funds road repairs that help commuters.", "trap": "trap.out_of_scope", "correct": False},
            {"id": "C", "text": "A subsidy helps farmers and lowers food prices.", "trap": "trap.out_of_scope", "correct": False},
            {"id": "D", "text": "A fee funds parks enjoyed by the payers.", "trap": "trap.out_of_scope", "correct": False},
            {"id": "E", "text": "A regulation protects workers and raises wages.", "trap": "trap.out_of_scope", "correct": False},
        ],
        "two_answer_fork": {"runner_up": "B", "why_runner_up_wrong": "B has compensating benefit; A burdens a group without offsetting societal gain."},
    },
    {
        "id": "lr-0027",
        "section": "LR",
        "stem_type": "qt.method_of_reasoning",
        "schemas": ["qt.method_of_reasoning"],
        "difficulty": 3,
        "source": "original",
        "stimulus": "The critic argues that the novel fails because its hero never changes; yet the hero's refusal to change is precisely what the author uses to critique society.",
        "question": "The argument responds by",
        "choices": [
            {"id": "A", "text": "claiming a feature treated as a flaw serves the author's purpose.", "trap": None, "correct": True},
            {"id": "B", "text": "denying that the hero exists.", "trap": "trap.opposite", "correct": False},
            {"id": "C", "text": "appealing to popular opinion.", "trap": "trap.out_of_scope", "correct": False},
            {"id": "D", "text": "asserting all novels must have changing heroes.", "trap": "trap.too_strong_extreme", "correct": False},
            {"id": "E", "text": "attacking the critic personally.", "trap": "trap.out_of_scope", "correct": False},
        ],
        "two_answer_fork": {"runner_up": "D", "why_runner_up_wrong": "D invents a rule; A reframes the alleged flaw as intentional."},
    },
    {
        "id": "lr-0028",
        "section": "LR",
        "stem_type": "qt.parallel_reasoning",
        "schemas": ["qt.parallel_reasoning"],
        "difficulty": 4,
        "source": "original",
        "stimulus": "If the server is down, emails queue. Emails are queuing, so the server is down.",
        "question": "Which argument has the most similar pattern?",
        "choices": [
            {"id": "A", "text": "If it rains, the game is canceled. The game is canceled, so it rained.", "trap": None, "correct": True},
            {"id": "B", "text": "If it rains, streets get wet. Streets are wet, so it rained.", "trap": "trap.half_right", "correct": False},
            {"id": "C", "text": "Only members may park here. Sam parked here, so Sam is a member.", "trap": "trap.reversed_relationship", "correct": False},
            {"id": "D", "text": "All dogs bark. Rex barks, so Rex is a dog.", "trap": "trap.reversed_relationship", "correct": False},
            {"id": "E", "text": "Either A or B. Not A, so B.", "trap": "trap.out_of_scope", "correct": False},
        ],
        "two_answer_fork": {"runner_up": "B", "why_runner_up_wrong": "B is also affirming the consequent but A matches the conditional structure of the stimulus more directly."},
    },
    {
        "id": "lr-0029",
        "section": "LR",
        "stem_type": "qt.main_conclusion",
        "schemas": ["qt.main_conclusion"],
        "difficulty": 2,
        "source": "original",
        "stimulus": "Since the river flooded twice this decade, and flood walls were never upgraded, the city should invest in levees now.",
        "question": "The main conclusion is that",
        "choices": [
            {"id": "A", "text": "the city should invest in levees now.", "trap": None, "correct": True},
            {"id": "B", "text": "the river flooded twice this decade.", "trap": "trap.premise_restatement", "correct": False},
            {"id": "C", "text": "flood walls were never upgraded.", "trap": "trap.premise_restatement", "correct": False},
            {"id": "D", "text": "levees always prevent flooding.", "trap": "trap.too_strong_extreme", "correct": False},
            {"id": "E", "text": "the decade is unusually wet.", "trap": "trap.out_of_scope", "correct": False},
        ],
        "two_answer_fork": {"runner_up": "B", "why_runner_up_wrong": "B is a premise; A is the recommendation (conclusion)."},
    },
    {
        "id": "lr-0030",
        "section": "LR",
        "stem_type": "qt.role_of_statement",
        "schemas": ["qt.role_of_statement"],
        "difficulty": 3,
        "source": "original",
        "stimulus": "The plan will fail unless costs fall. Costs have not fallen. Therefore the plan will fail.",
        "question": "The claim that costs have not fallen plays which role?",
        "choices": [
            {"id": "A", "text": "It is a premise supporting the conclusion.", "trap": None, "correct": True},
            {"id": "B", "text": "It is the main conclusion.", "trap": "trap.premise_restatement", "correct": False},
            {"id": "C", "text": "It is background context with no logical role.", "trap": "trap.out_of_scope", "correct": False},
            {"id": "D", "text": "It is an intermediate conclusion.", "trap": "trap.half_right", "correct": False},
            {"id": "E", "text": "It contradicts the argument.", "trap": "trap.opposite", "correct": False},
        ],
        "two_answer_fork": {"runner_up": "D", "why_runner_up_wrong": "D overstates; the statement is a direct premise, not a sub-conclusion."},
    },
    {
        "id": "lr-0031",
        "section": "LR",
        "stem_type": "qt.point_at_issue",
        "schemas": ["qt.point_at_issue"],
        "difficulty": 3,
        "source": "original",
        "stimulus": "Alex: The policy reduced crime. Jordan: Crime fell everywhere this year, so we can't credit the policy.",
        "question": "Alex and Jordan disagree over whether",
        "choices": [
            {"id": "A", "text": "the policy caused the local crime reduction.", "trap": None, "correct": True},
            {"id": "B", "text": "crime fell locally.", "trap": "trap.premise_restatement", "correct": False},
            {"id": "C", "text": "crime is measurable.", "trap": "trap.out_of_scope", "correct": False},
            {"id": "D", "text": "policies ever work.", "trap": "trap.too_strong_extreme", "correct": False},
            {"id": "E", "text": "Jordan supports the policy.", "trap": "trap.out_of_scope", "correct": False},
        ],
        "two_answer_fork": {"runner_up": "B", "why_runner_up_wrong": "Both accept local decline; they dispute causation (A)."},
    },
    {
        "id": "lr-0032",
        "section": "LR",
        "stem_type": "qt.evaluate",
        "schemas": ["qt.evaluate"],
        "difficulty": 3,
        "source": "original",
        "stimulus": "The new curriculum improved test scores, so it should be adopted nationwide.",
        "question": "Which would be most useful to evaluate the argument?",
        "choices": [
            {"id": "A", "text": "Whether other factors changed in the pilot schools at the same time.", "trap": None, "correct": True},
            {"id": "B", "text": "Whether teachers liked the curriculum.", "trap": "trap.out_of_scope", "correct": False},
            {"id": "C", "text": "Whether students enjoy school.", "trap": "trap.out_of_scope", "correct": False},
            {"id": "D", "text": "Whether textbooks are expensive.", "trap": "trap.out_of_scope", "correct": False},
            {"id": "E", "text": "Whether the nation has many schools.", "trap": "trap.out_of_scope", "correct": False},
        ],
        "two_answer_fork": {"runner_up": "B", "why_runner_up_wrong": "B is tangential; A tests whether the curriculum caused the gain."},
    },
    {
        "id": "rc-0002-q1",
        "section": "RC",
        "stem_type": "rc.passage_organization",
        "schemas": ["rc.passage_organization"],
        "difficulty": 3,
        "source": "original",
        "passage_id": "rc-0002",
        "passage": "Biologists long classified species by visible traits alone. Molecular tools later revealed hidden lineages, forcing revisions. Some researchers resisted, fearing instability in nomenclature; others welcomed finer resolution. The debate continues, but most now treat morphology and genetics as complementary rather than competing.",
        "question": "Which best describes the organization of the passage?",
        "choices": [
            {"id": "A", "text": "An older method is described, a challenge is introduced, and a reconciling view is offered.", "trap": None, "correct": True},
            {"id": "B", "text": "Two competing theories are shown to be equally false.", "trap": "trap.rc.wrong_viewpoint", "correct": False},
            {"id": "C", "text": "A hypothesis is tested by a single experiment.", "trap": "trap.out_of_scope", "correct": False},
            {"id": "D", "text": "Chronological biography of a scientist.", "trap": "trap.out_of_scope", "correct": False},
            {"id": "E", "text": "A problem is stated without resolution.", "trap": "trap.rc.tone_mismatch", "correct": False},
        ],
        "two_answer_fork": {"runner_up": "E", "why_runner_up_wrong": "The passage resolves toward complementarity; A matches the structure."},
    },
    {
        "id": "rc-0002-q2",
        "section": "RC",
        "stem_type": "rc.viewpoint_attribution",
        "schemas": ["rc.viewpoint_attribution"],
        "difficulty": 3,
        "source": "original",
        "passage_id": "rc-0002",
        "passage": "(see rc-0002)",
        "question": "According to the passage, researchers who resisted molecular revisions were primarily concerned about",
        "choices": [
            {"id": "A", "text": "instability in nomenclature.", "trap": None, "correct": True},
            {"id": "B", "text": "the cost of laboratory equipment.", "trap": "trap.out_of_scope", "correct": False},
            {"id": "C", "text": "public misunderstanding of genetics.", "trap": "trap.out_of_scope", "correct": False},
            {"id": "D", "text": "the superiority of morphology.", "trap": "trap.rc.distortion_author_view", "correct": False},
            {"id": "E", "text": "abandoning all visible-trait classification.", "trap": "trap.too_strong_extreme", "correct": False},
        ],
        "two_answer_fork": {"runner_up": "E", "why_runner_up_wrong": "E overstates; the passage cites nomenclature stability (A)."},
    },
    {
        "id": "rc-0002-q3",
        "section": "RC",
        "stem_type": "rc.inference",
        "schemas": ["rc.inference"],
        "difficulty": 3,
        "source": "original",
        "passage_id": "rc-0002",
        "passage": "(see rc-0002)",
        "question": "It can be inferred that the author would most likely agree that",
        "choices": [
            {"id": "A", "text": "combining morphological and genetic data improves classification.", "trap": None, "correct": True},
            {"id": "B", "text": "molecular tools should replace morphology entirely.", "trap": "trap.too_strong_extreme", "correct": False},
            {"id": "C", "text": "resistance to revision was entirely unreasonable.", "trap": "trap.too_strong_extreme", "correct": False},
            {"id": "D", "text": "visible traits are useless for biology.", "trap": "trap.opposite", "correct": False},
            {"id": "E", "text": "the debate has been settled permanently.", "trap": "trap.too_strong_extreme", "correct": False},
        ],
        "two_answer_fork": {"runner_up": "B", "why_runner_up_wrong": "Author favors complementarity, not replacement (A)."},
    },
    {
        "id": "rc-0002-q4",
        "section": "RC",
        "stem_type": "rc.comparative_relationship",
        "schemas": ["rc.comparative_relationship"],
        "difficulty": 4,
        "source": "original",
        "passage_id": "rc-0002",
        "passage": "(see rc-0002)",
        "question": "The relationship between morphology-based classification and molecular classification is best described as",
        "choices": [
            {"id": "A", "text": "initially sequential, later treated as mutually informative.", "trap": None, "correct": True},
            {"id": "B", "text": "entirely unrelated disciplines.", "trap": "trap.opposite", "correct": False},
            {"id": "C", "text": "identical in practice.", "trap": "trap.too_strong_extreme", "correct": False},
            {"id": "D", "text": "one disproving the other completely.", "trap": "trap.rc.wrong_viewpoint", "correct": False},
            {"id": "E", "text": "competitive with no overlap.", "trap": "trap.rc.wrong_viewpoint", "correct": False},
        ],
        "two_answer_fork": {"runner_up": "E", "why_runner_up_wrong": "Passage ends with complementarity; A captures historical then integrative relation."},
    },
    {
        "id": "lr-0033",
        "section": "LR",
        "stem_type": "qt.strengthen",
        "schemas": ["trap.could_be_true", "qt.strengthen"],
        "difficulty": 2,
        "source": "original",
        "stimulus": "The witness saw a red car flee the scene, so the suspect's red car places him at the scene.",
        "question": "Which strengthens the argument?",
        "choices": [
            {"id": "A", "text": "No other red cars were reported in the area that night.", "trap": None, "correct": True},
            {"id": "B", "text": "The suspect owns a red car.", "trap": "trap.could_be_true", "correct": False},
            {"id": "C", "text": "Red cars are common.", "trap": "trap.opposite", "correct": False},
            {"id": "D", "text": "The witness wears glasses.", "trap": "trap.out_of_scope", "correct": False},
            {"id": "E", "text": "The suspect denies being there.", "trap": "trap.opposite", "correct": False},
        ],
        "two_answer_fork": {"runner_up": "B", "why_runner_up_wrong": "B could be true but doesn't strengthen identification; A reduces alternative red-car sources."},
    },
    {
        "id": "lr-0034",
        "section": "LR",
        "stem_type": "qt.weaken",
        "schemas": ["trap.real_world_plausible", "qt.weaken"],
        "difficulty": 2,
        "source": "original",
        "stimulus": "Organic foods are healthier because they are natural.",
        "question": "Which weakens the argument?",
        "choices": [
            {"id": "A", "text": "Many natural substances are harmful and many processed foods are safe.", "trap": None, "correct": True},
            {"id": "B", "text": "Organic farming uses more land.", "trap": "trap.out_of_scope", "correct": False},
            {"id": "C", "text": "Consumers prefer organic labels.", "trap": "trap.out_of_scope", "correct": False},
            {"id": "D", "text": "Some organic foods taste better.", "trap": "trap.real_world_plausible", "correct": False},
            {"id": "E", "text": "Farmers markets are popular.", "trap": "trap.out_of_scope", "correct": False},
        ],
        "two_answer_fork": {"runner_up": "D", "why_runner_up_wrong": "D is plausible but irrelevant to health; A attacks the natural=healthy assumption."},
    },
]


def main() -> None:
    data = json.loads(SEED.read_text(encoding="utf-8"))
    existing = {item["id"] for item in data["items"]}
    added = 0
    for item in NEW_ITEMS:
        if item["id"] not in existing:
            data["items"].append(item)
            added += 1
    data["version"] = "0.2.0"
    SEED.write_text(json.dumps(data, indent=4) + "\n", encoding="utf-8")
    print(f"Total items: {len(data['items'])} (+{added} new)")


if __name__ == "__main__":
    main()
